/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui.Maintenance.Staff;

/**
 *
 * @author limzh
 */
import Control.*;
import Da.*;
import Domain.*;
import javax.swing.JOptionPane;

public class Add_Staff extends javax.swing.JFrame {

    private MaintainStaffControl staffControl;

    public Add_Staff() {
        staffControl = new MaintainStaffControl();
        String id = staffControl.GetNewStaffCode();

        initComponents();
        setSize(700, 630);
        staffid.setText(id);
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        setTitle("Add Staff");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        staffid = new javax.swing.JTextField();
        staffname = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        staffaddress = new javax.swing.JTextArea();
        password1 = new javax.swing.JPasswordField();
        password2 = new javax.swing.JPasswordField();
        confirm = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        position1 = new javax.swing.JComboBox();
        contactno = new javax.swing.JFormattedTextField();
        staffic = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Staff ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 50, 180, 40);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Staff Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 100, 180, 40);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("I.C Number");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(130, 150, 180, 38);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Address");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(130, 200, 180, 42);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Contact Number");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(130, 320, 180, 40);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Position");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(130, 370, 180, 41);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Password");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(130, 420, 180, 41);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Confirm Password");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(130, 470, 180, 41);

        staffid.setEditable(false);
        getContentPane().add(staffid);
        staffid.setBounds(310, 50, 230, 42);
        getContentPane().add(staffname);
        staffname.setBounds(310, 100, 230, 40);

        staffaddress.setColumns(20);
        staffaddress.setRows(5);
        jScrollPane1.setViewportView(staffaddress);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(310, 200, 230, 108);
        getContentPane().add(password1);
        password1.setBounds(310, 420, 230, 40);
        getContentPane().add(password2);
        password2.setBounds(310, 470, 230, 43);

        confirm.setText("Confirm");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });
        getContentPane().add(confirm);
        confirm.setBounds(200, 550, 90, 30);

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset);
        reset.setBounds(350, 550, 90, 30);

        position1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "Manager", "Clerk", "Receiptionist", "Bus Driver" }));
        position1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                position1ActionPerformed(evt);
            }
        });
        getContentPane().add(position1);
        position1.setBounds(310, 370, 230, 40);

        try {
            contactno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-#######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        contactno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactnoActionPerformed(evt);
            }
        });
        getContentPane().add(contactno);
        contactno.setBounds(310, 320, 230, 40);

        try {
            staffic.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("######-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(staffic);
        staffic.setBounds(310, 150, 230, 40);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 690, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void position1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_position1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_position1ActionPerformed

    private void contactnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactnoActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        password1.setText(null);
        password2.setText(null);
        staffaddress.setText(null);
        staffname.setText(null);
        contactno.setText(null);
        staffic.setText(null);
        staffic.setValue(null);
        contactno.setValue(null);
        position1.setSelectedItem("-");
    }//GEN-LAST:event_resetActionPerformed

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed

        String pass1 = password1.getText();
        String pass2 = password2.getText();
        String adrs = staffaddress.getText();
        String position = String.valueOf(position1.getSelectedItem());
        String id = staffid.getText();
        String name = staffname.getText().toUpperCase();
        String c_no = contactno.getText();
        String ic = staffic.getText();

        if (validation() == true) {

            Staff staff = new Staff(id, name, ic, adrs, c_no, position, pass2);
            staffControl.addRecord(staff);
            JOptionPane.showMessageDialog(null, "New staff added successfully.",
                    "Staff Added", JOptionPane.INFORMATION_MESSAGE);
            staffid.setText(staffControl.GetNewStaffCode());
            password1.setText(null);
            password2.setText(null);
            staffaddress.setText(null);
            staffname.setText(null);
            contactno.setText(null);
            staffic.setText(null);
            staffic.setValue(null);
            contactno.setValue(null);
            position1.setSelectedItem("-");
        }
    }//GEN-LAST:event_confirmActionPerformed

    public boolean validation() {
        if (staffname.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Please enter the staff name.",
                    "Invalid Name", JOptionPane.ERROR_MESSAGE);
            staffname.grabFocus();
            return false;
        } else if ((staffic.getText().trim().length() == 2)
                || (staffic.getText().trim().length() < 14)) {
            JOptionPane.showMessageDialog(null, "Please enter the IC number. eg.160322-08-1234",
                    "Invalid IC", JOptionPane.ERROR_MESSAGE);
            staffic.grabFocus();

            return false;
        } else if ((staffaddress.getText().trim().length() == 0)) {
            JOptionPane.showMessageDialog(null, "Please enter the staff address.",
                    "Invalid Staff Address", JOptionPane.ERROR_MESSAGE);
            staffaddress.grabFocus();

            return false;
        } else if ((contactno.getText().trim().length() == 0)
                || (contactno.getText().trim().length() < 11)) {
            JOptionPane.showMessageDialog(null, "Please enter the Contact No. eg.012-3456789",
                    "Invalid Contact Number", JOptionPane.ERROR_MESSAGE);
            contactno.grabFocus();

            return false;
        } else if ((position1.getSelectedItem() == "-")) {
            JOptionPane.showMessageDialog(null, "Please selection the staff position",
                    "Invalid selection", JOptionPane.ERROR_MESSAGE);
            contactno.grabFocus();

            return false;
        } else if (password1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter the password",
                    "Password empty", JOptionPane.ERROR_MESSAGE);
            password1.grabFocus();
            return false;
        } else if (password1.getText().trim().length() < 5) {
            JOptionPane.showMessageDialog(null, "Please enter atleast 6 alphanumeric password",
                    "Invalid Format", JOptionPane.ERROR_MESSAGE);
            password1.grabFocus();
            return false;
        } else if (password2.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter the confirm password",
                    "Password empty", JOptionPane.ERROR_MESSAGE);
            password2.grabFocus();
            return false;
        } else if (password2.getText().trim().length() < 5) {
            JOptionPane.showMessageDialog(null, "Please enter atleast 6 alphanumeric password",
                    "Invalid format", JOptionPane.ERROR_MESSAGE);
            password2.grabFocus();
            return false;
        } else if (!password1.getText().equals(password2.getText())) {
            JOptionPane.showMessageDialog(null, "Confirm Password not matches.",
                    "Password Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Staff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirm;
    private javax.swing.JFormattedTextField contactno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPasswordField password1;
    private javax.swing.JPasswordField password2;
    private javax.swing.JComboBox position1;
    private javax.swing.JButton reset;
    private javax.swing.JTextArea staffaddress;
    private javax.swing.JFormattedTextField staffic;
    private javax.swing.JTextField staffid;
    private javax.swing.JTextField staffname;
    // End of variables declaration//GEN-END:variables
}
