/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui;

import Da.StaffDa;
import javax.swing.JOptionPane;

/**
 *
 * @author Guanhaochan
 */
public class RecoveryPassword extends javax.swing.JFrame {

    /**
     * Creates new form RecoveryPassword
     */
    private StaffDa staffDa;

    public RecoveryPassword() {
        initComponents();
        setSize(400, 300);
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        setTitle("RecoverPassword");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Staff IC :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 150, 80, 30);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Staff ID :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 70, 80, 30);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Staff Name  :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 110, 80, 30);

        jButton2.setText("Confirm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(90, 200, 80, 30);

        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(200, 200, 80, 30);

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("######-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormattedTextField1);
        jFormattedTextField1.setBounds(180, 150, 120, 30);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(180, 110, 120, 30);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(180, 70, 120, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/5.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        staffDa = new StaffDa();
        String id = jTextField2.getText().toUpperCase();
        String name = jTextField1.getText().toUpperCase();
        String ic = jFormattedTextField1.getText();
        if (validation() == true) {
            int i = staffDa.verifyRecoverPassword(id, name, ic);

            if (i == 1) {
                dispose();
            } else {
                jFormattedTextField1.setValue(null);
                jFormattedTextField1.setText(null);
                jTextField1.setText(null);
                jTextField2.setText(null);
            }
        }

    }//GEN-LAST:event_jButton2ActionPerformed
    public boolean validation() {
        if (jTextField2.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter your Staff ID eg. S99",
                    "Invalid Staff ID", JOptionPane.ERROR_MESSAGE);
            jTextField2.grabFocus();
            return false;
        } else if (jTextField2.getText().trim().length() > 4) {
            JOptionPane.showMessageDialog(null, "Please enter 1 - 4 alphanumeric eg. S99",
                    "Invalid Format", JOptionPane.ERROR_MESSAGE);
            jTextField2.grabFocus();
            return false;
        } else if ((jTextField1.getText().trim().length() == 0)) {
            JOptionPane.showMessageDialog(null, "Please enter your Staff Name",
                    "Invalid Staff Name", JOptionPane.ERROR_MESSAGE);
            jTextField1.grabFocus();

            return false;
        } else if (jFormattedTextField1.getText().trim().length() < 14) {
            JOptionPane.showMessageDialog(null, "Please enter  14 alphanumeric eg.901234-08-5142",
                    "Invalid Format", JOptionPane.ERROR_MESSAGE);
            jTextField2.grabFocus();
            return false;
        }

        return true;
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jFormattedTextField1.setText(null);
        jTextField1.setText(null);
        jTextField2.setText(null);
        jFormattedTextField1.setValue(null);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecoveryPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecoveryPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecoveryPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecoveryPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecoveryPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
