/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui.Maintenance.Member;

/**
 *
 * @author limzh
 */
import Ui.Maintenance.Member.*;
import Control.*;
import Da.*;
import Domain.*;
import javax.swing.JOptionPane;

public class Add_Member extends javax.swing.JFrame {

    private MaintainMemberControl memberControl;

    public Add_Member() {
        memberControl = new MaintainMemberControl();
        String id = memberControl.GetNewMemberCode();

        initComponents();
        setSize(676, 500);
        memberid.setText(id);
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        setTitle("Add Member");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        memberid = new javax.swing.JTextField();
        membername = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        memberaddress = new javax.swing.JTextArea();
        confirm = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        contactno = new javax.swing.JFormattedTextField();
        memberic = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Member ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 60, 190, 42);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Member Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 110, 190, 42);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("I.C Number");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(130, 160, 190, 38);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Address");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(130, 210, 190, 40);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Contact Number");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(130, 330, 190, 40);

        memberid.setEditable(false);
        getContentPane().add(memberid);
        memberid.setBounds(320, 60, 230, 42);
        getContentPane().add(membername);
        membername.setBounds(320, 110, 230, 40);

        memberaddress.setColumns(20);
        memberaddress.setRows(5);
        jScrollPane1.setViewportView(memberaddress);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(320, 210, 230, 108);

        confirm.setText("Confirm");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });
        getContentPane().add(confirm);
        confirm.setBounds(220, 410, 90, 30);

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset);
        reset.setBounds(350, 410, 90, 30);

        try {
            contactno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-#######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        contactno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactnoActionPerformed(evt);
            }
        });
        getContentPane().add(contactno);
        contactno.setBounds(320, 330, 230, 40);

        try {
            memberic.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("######-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(memberic);
        memberic.setBounds(320, 160, 230, 40);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 690, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contactnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactnoActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed

        memberaddress.setText(null);
        membername.setText(null);
        contactno.setText(null);
        memberic.setText(null);
        memberic.setValue(null);
        contactno.setValue(null);
    }//GEN-LAST:event_resetActionPerformed

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed

        String adrs = memberaddress.getText();
        String id = memberid.getText();
        String name = membername.getText().toUpperCase();
        String c_no = contactno.getText();
        String ic = memberic.getText();

        if (validation() == true) {

            Member member = new Member(id, name, ic, adrs, c_no);
            memberControl.addRecord(member);
            JOptionPane.showMessageDialog(null, "New member added successfully.",
                    "Member Added", JOptionPane.INFORMATION_MESSAGE);
            memberid.setText(memberControl.GetNewMemberCode());
            memberaddress.setText(null);
            membername.setText(null);
            contactno.setText(null);
            memberic.setText(null);
            memberic.setValue(null);
            contactno.setValue(null);
        }
    }//GEN-LAST:event_confirmActionPerformed

    public boolean validation() {
        if (membername.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Please enter the member name.",
                    "Invalid Name", JOptionPane.ERROR_MESSAGE);
            membername.grabFocus();
            return false;
        } else if ((memberic.getText().trim().length() == 0)
                || (memberic.getText().trim().length() < 14)) {
            JOptionPane.showMessageDialog(null, "IC must have 12 Digit. eg.160322-08-1234",
                    "Invalid IC", JOptionPane.ERROR_MESSAGE);
            memberic.grabFocus();
            return false;
        } else if ((memberaddress.getText().trim().length() == 0)) {
            JOptionPane.showMessageDialog(null, "Please enter the member address.",
                    "Invalid Member Address", JOptionPane.ERROR_MESSAGE);
            memberaddress.grabFocus();
            return false;
        } else if ((contactno.getText().trim().length() == 0)
                || (contactno.getText().trim().length() < 11)) {
            JOptionPane.showMessageDialog(null, "Contact Number must be 10 Digit. 012-3456789",
                    "Invalid Contact Number", JOptionPane.ERROR_MESSAGE);
            contactno.grabFocus();
            return false;
        }
        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Member().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirm;
    private javax.swing.JFormattedTextField contactno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea memberaddress;
    private javax.swing.JFormattedTextField memberic;
    private javax.swing.JTextField memberid;
    private javax.swing.JTextField membername;
    private javax.swing.JButton reset;
    // End of variables declaration//GEN-END:variables
}
