/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui.Maintenance.Bus;

import Da.BusDa;
import Domain.Bus;
import Control.MaintainBusControl;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Guanhaochan
 */
public class Add_Bus extends javax.swing.JFrame {

    private String host = "jdbc:derby://localhost:1527/FYP database";
    private String user = "nbuser";
    private String password = "nbuser";
    private Connection conn;
    private PreparedStatement stmt;
    private MaintainBusControl busControl;
    public String staffbus_id;
    public String staff_id;

    public Add_Bus() {
        busControl = new MaintainBusControl();
        String id = busControl.GetNewBusCode();
        createConnection();
        initComponents();
        RetrieveValueToComboBox();
        //RetrieveBusToComboBox();
       /* for (int x = 0; x < 100; x++) {
         if (staff_id1[x].equalsIgnoreCase(staffbus_id[x])) {
         staffcombo.addItem(staffbus_id[x]);
         }

         }*/
        BusID.setText(id);
        setSize(536, 358);
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        setTitle("Add Bus");
    }

    private void RetrieveValueToComboBox() {
        try {
            String sql = "SELECT * FROM STAFF BUS WHERE POSITION = 'Bus Driver'";
            stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            while (rs.next()) {

                staff_id = rs.getString(1);
                staffcombo.addItem(staff_id);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    /*private void RetrieveBusToComboBox() {
     try {
     String sql = "SELECT * FROM BUS";
     stmt = conn.prepareStatement(sql);
     ResultSet rs = stmt.executeQuery();
     while (rs.next()) {

     //staffbus_id[i] = rs.getString(5);
              
     }
     } catch (Exception ex) {
     JOptionPane.showMessageDialog(null, ex);
     }
     }*/
    private void createConnection() {
        try {
            conn = DriverManager.getConnection(host, user, password);
            System.out.println("***TRACE: Connection established.");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void shutDown() {
        if (conn != null) {
            try {
                conn.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        busid = new javax.swing.JLabel();
        BusID = new javax.swing.JTextField();
        busnolabel = new javax.swing.JLabel();
        seatlabel = new javax.swing.JLabel();
        modellabel = new javax.swing.JLabel();
        stafflabel = new javax.swing.JLabel();
        staffcombo = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        buscombo = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        busno = new javax.swing.JTextField();
        seatno = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        busid.setForeground(new java.awt.Color(255, 255, 255));
        busid.setText("Bus ID");
        getContentPane().add(busid);
        busid.setBounds(130, 40, 60, 30);

        BusID.setEditable(false);
        BusID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusIDActionPerformed(evt);
            }
        });
        getContentPane().add(BusID);
        BusID.setBounds(260, 40, 120, 30);

        busnolabel.setForeground(new java.awt.Color(255, 255, 255));
        busnolabel.setText("Bus No");
        getContentPane().add(busnolabel);
        busnolabel.setBounds(130, 80, 60, 30);

        seatlabel.setForeground(new java.awt.Color(255, 255, 255));
        seatlabel.setText("Number of Seat");
        getContentPane().add(seatlabel);
        seatlabel.setBounds(130, 120, 100, 30);

        modellabel.setForeground(new java.awt.Color(255, 255, 255));
        modellabel.setText("Bus Model");
        getContentPane().add(modellabel);
        modellabel.setBounds(130, 160, 100, 30);

        stafflabel.setForeground(new java.awt.Color(255, 255, 255));
        stafflabel.setText("Staff ID");
        getContentPane().add(stafflabel);
        stafflabel.setBounds(130, 200, 100, 30);

        staffcombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-" }));
        getContentPane().add(staffcombo);
        staffcombo.setBounds(260, 200, 120, 30);

        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(140, 260, 90, 30);

        buscombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "BUGATTE", "AUDE", "PORCHE", "BNW", "BANS", "TOYATA" }));
        getContentPane().add(buscombo);
        buscombo.setBounds(260, 160, 120, 30);

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(280, 260, 90, 30);
        getContentPane().add(busno);
        busno.setBounds(260, 80, 120, 30);

        seatno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatnoActionPerformed(evt);
            }
        });
        seatno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                seatnoKeyTyped(evt);
            }
        });
        getContentPane().add(seatno);
        seatno.setBounds(260, 120, 120, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 540, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BusIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BusIDActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String id = BusID.getText();
        String bus_no = busno.getText().toUpperCase();

        String model = String.valueOf(buscombo.getSelectedItem());
        String staff_id = String.valueOf(staffcombo.getSelectedItem());

        if (validation() == true) {
            int seat = Integer.parseInt(seatno.getText());
            Bus bus = new Bus(id, bus_no, seat, model, staff_id);
            busControl.addRecord(bus);
            JOptionPane.showMessageDialog(null, "Bus added successfully.",
                    "Bus Added", JOptionPane.INFORMATION_MESSAGE);
            BusID.setText(busControl.GetNewBusCode());
            busid.setText(busControl.GetNewBusCode());
            busno.setText(null);
            seatno.setText(null);
            buscombo.setSelectedItem("-");
            staffcombo.setSelectedItem("-");
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        busno.setText(null);
        seatno.setText(null);
        buscombo.setSelectedItem("-");
        staffcombo.setSelectedItem("-");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void seatnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_seatnoKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            evt.consume();
        }
    }//GEN-LAST:event_seatnoKeyTyped

    private void seatnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatnoActionPerformed

    }//GEN-LAST:event_seatnoActionPerformed

    public boolean validation() {

        if (busno.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Please enter the Bus No. "
                    + "eg.ABC1234",
                    "Invalid Bus No", JOptionPane.ERROR_MESSAGE);
            busno.grabFocus();
            return false;
        } else if ((busno.getText().trim().length() > 7)) {
            JOptionPane.showMessageDialog(null, "Please enter not more than 7  alphanumeric in Bus No. "
                    + "eg.ABC1234",
                    "Invalid Format Bus No", JOptionPane.ERROR_MESSAGE);
            busno.grabFocus();
            return false;
        } else if ((busno.getText().trim().length() < 7)) {
            JOptionPane.showMessageDialog(null, "Please enter not less than 7  alphanumeric in Bus No. "
                    + "eg.ABC1234",
                    "Invalid Format Bus No", JOptionPane.ERROR_MESSAGE);
            busno.grabFocus();
            return false;
        } else if ((seatno.getText().trim().length() == 0)) {
            JOptionPane.showMessageDialog(null, "Please enter the Number of Seat. eg.25",
                    "Invalid Seat number", JOptionPane.ERROR_MESSAGE);
            seatno.grabFocus();
            return false;
        } else if ((seatno.getText().trim().length() > 2)) {
            JOptionPane.showMessageDialog(null, "Please not more than 2 numeric. eg.25",
                    "Invalid Format", JOptionPane.ERROR_MESSAGE);
            seatno.grabFocus();
            return false;
        } else if ((seatno.getText().trim().length() < 2)) {
            JOptionPane.showMessageDialog(null, "Please not less than 2 numeric. eg.25",
                    "Invalid Format", JOptionPane.ERROR_MESSAGE);
            seatno.grabFocus();
            return false;
        } else if ((buscombo.getSelectedItem() == "-")) {
            JOptionPane.showMessageDialog(null, "Please select the bus model.",
                    "Invalid selection", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if ((staffcombo.getSelectedItem() == "-")) {
            JOptionPane.showMessageDialog(null, "Please select the staff id.",
                    "Invalid selection", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Bus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Bus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Bus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Bus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Bus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BusID;
    private javax.swing.JComboBox buscombo;
    private javax.swing.JLabel busid;
    private javax.swing.JTextField busno;
    private javax.swing.JLabel busnolabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel modellabel;
    private javax.swing.JLabel seatlabel;
    private javax.swing.JTextField seatno;
    private javax.swing.JComboBox staffcombo;
    private javax.swing.JLabel stafflabel;
    // End of variables declaration//GEN-END:variables
}
