/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui.Maintenance.Bus;

import Control.MaintainBusControl;
import Domain.Bus;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Guanhaochan
 */
public class Delete_Bus extends javax.swing.JFrame {

    private String host = "jdbc:derby://localhost:1527/FYP database";
    private String user = "nbuser";
    private String password = "nbuser";
    private Connection conn;
    private PreparedStatement stmt;
    private MaintainBusControl busControl;
    private Bus bus;

    public Delete_Bus() {
        busControl = new MaintainBusControl();
        createConnection();
        initComponents();
        RetrieveBusIDToComboBox();
        setSize(493, 362);
        setResizable(false);
        jButton1.setEnabled(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        setTitle("Delete Bus");
    }

    private void RetrieveBusIDToComboBox() {
        try {
            String sql = "select * from BUS";
            stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            while (rs.next()) {

                String id = rs.getString(1);
                busId.addItem(id);

            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    private void createConnection() {
        try {
            conn = DriverManager.getConnection(host, user, password);
            System.out.println("***TRACE: Connection established.");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void shutDown() {
        if (conn != null) {
            try {
                conn.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        stafflabel = new javax.swing.JLabel();
        modellabel = new javax.swing.JLabel();
        seatno = new javax.swing.JFormattedTextField();
        seatlabel = new javax.swing.JLabel();
        busno = new javax.swing.JFormattedTextField();
        busnolabel = new javax.swing.JLabel();
        busid = new javax.swing.JLabel();
        busId = new javax.swing.JComboBox();
        search = new javax.swing.JButton();
        buscombo = new javax.swing.JTextField();
        staffcombo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(110, 260, 90, 30);

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(240, 260, 90, 30);

        stafflabel.setForeground(new java.awt.Color(255, 255, 255));
        stafflabel.setText("Staff ID");
        getContentPane().add(stafflabel);
        stafflabel.setBounds(90, 200, 100, 30);

        modellabel.setForeground(new java.awt.Color(255, 255, 255));
        modellabel.setText("Bus Model");
        getContentPane().add(modellabel);
        modellabel.setBounds(90, 160, 100, 30);

        seatno.setEditable(false);
        try {
            seatno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(seatno);
        seatno.setBounds(220, 120, 120, 30);

        seatlabel.setForeground(new java.awt.Color(255, 255, 255));
        seatlabel.setText("Number of Seat");
        getContentPane().add(seatlabel);
        seatlabel.setBounds(90, 120, 100, 30);

        busno.setEditable(false);
        try {
            busno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("***####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(busno);
        busno.setBounds(220, 80, 120, 30);

        busnolabel.setForeground(new java.awt.Color(255, 255, 255));
        busnolabel.setText("Bus No");
        getContentPane().add(busnolabel);
        busnolabel.setBounds(90, 80, 60, 30);

        busid.setForeground(new java.awt.Color(255, 255, 255));
        busid.setText("Bus ID");
        getContentPane().add(busid);
        busid.setBounds(90, 40, 60, 30);

        busId.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-" }));
        getContentPane().add(busId);
        busId.setBounds(220, 40, 120, 30);

        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search);
        search.setBounds(370, 40, 90, 30);

        buscombo.setEditable(false);
        buscombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscomboActionPerformed(evt);
            }
        });
        getContentPane().add(buscombo);
        buscombo.setBounds(220, 160, 120, 30);

        staffcombo.setEditable(false);
        getContentPane().add(staffcombo);
        staffcombo.setBounds(220, 200, 120, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 490, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (validation() == true) {
            int n = JOptionPane.showConfirmDialog(null, "Are you sure want to delete it?",
                    "RECORD DELETED", JOptionPane.OK_CANCEL_OPTION);
            if (n == JOptionPane.OK_OPTION) {
                busControl.DeleteRecord(bus);
                busId.removeAllItems();
                busId.addItem("-");
            }
            try {
                String sql = "select * from BUS";
                stmt = conn.prepareStatement(sql);
                ResultSet rs = stmt.executeQuery();
                while (rs.next()) {

                    String id = rs.getString(1);
                    busId.addItem(id);

                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
            busno.setText(null);
            seatno.setText(null);
            buscombo.setText(null);
            staffcombo.setText(null);
            jButton1.setEnabled(false);

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jButton1.setEnabled(false);
        busno.setText(null);
        seatno.setText(null);
        buscombo.setText(null);
        staffcombo.setText(null);
        busId.setSelectedItem("-");
    }//GEN-LAST:event_jButton2ActionPerformed

    public boolean validation() {
        if ((busId.getSelectedItem() == "-")) {
            JOptionPane.showMessageDialog(null, "Please select the bus id",
                    "Invalid selection", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        if ((busId.getSelectedItem() == "-")) {
            JOptionPane.showMessageDialog(null, "Please select the bus id",
                    "Invalid selection", JOptionPane.ERROR_MESSAGE);
        } else {
            String id = String.valueOf(busId.getSelectedItem());
            bus = busControl.selectRecord(id);
            jButton1.setEnabled(true);
            busno.setText(bus.getBUS_NO());
            seatno.setText(String.valueOf(bus.getSEAT()));
            buscombo.setText(bus.getBUS_MODEL());
            staffcombo.setText(bus.getSTAFF_ID());
        }
    }//GEN-LAST:event_searchActionPerformed

    private void buscomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscomboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Delete_Bus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Delete_Bus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Delete_Bus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Delete_Bus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Delete_Bus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox busId;
    private javax.swing.JTextField buscombo;
    private javax.swing.JLabel busid;
    private javax.swing.JFormattedTextField busno;
    private javax.swing.JLabel busnolabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel modellabel;
    private javax.swing.JButton search;
    private javax.swing.JLabel seatlabel;
    private javax.swing.JFormattedTextField seatno;
    private javax.swing.JTextField staffcombo;
    private javax.swing.JLabel stafflabel;
    // End of variables declaration//GEN-END:variables
}
