/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui.Maintenance.Bus;

import Control.MaintainStaffControl;
import Da.StaffDa;
import Domain.Staff;
import Ui.Maintenance.Staff.StaffSearch_Record;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Guanhaochan
 */
public class Search_Bus extends javax.swing.JFrame {

    private String host = "jdbc:derby://localhost:1527/FYP database";
    private String user = "nbuser";
    private String password = "nbuser";
    private Connection conn;
    private PreparedStatement stmt;
    private StaffDa staffDa;
    private Staff staff;
    private MaintainStaffControl staffControl;

    public Search_Bus() {
        createConnection();
        initComponents();
        RetrieveBusIDToComboBox();
        RetrieveStaffIDToComboBox();
        setSize(567, 355);

        buttonradio.add(idradio);
        buttonradio.add(nameradio);
        buttonradio.add(positionradio);
        idradio.setSelected(true);
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        setTitle("Search Bus");
    }

    private void RetrieveBusIDToComboBox() {
        try {
            String sql = "select * from BUS";
            stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();

            while (rs.next()) {
                String id = rs.getString(1);
                idcombo.addItem(id);

            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    private void RetrieveStaffIDToComboBox() {
        try {
            String sql = "select * from STAFF WHERE POSITION = 'Bus Driver'";
            stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();

            while (rs.next()) {
                String id = rs.getString(1);
                staffcombo.addItem(id);

            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    private void createConnection() {
        try {
            conn = DriverManager.getConnection(host, user, password);
            System.out.println("***TRACE: Connection established.");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void shutDown() {
        if (conn != null) {
            try {
                conn.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonradio = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        model = new javax.swing.JLabel();
        busmodelcombo = new javax.swing.JComboBox();
        staffid = new javax.swing.JLabel();
        staffcombo = new javax.swing.JComboBox();
        idcombo = new javax.swing.JComboBox();
        busid = new javax.swing.JLabel();
        idradio = new javax.swing.JRadioButton();
        nameradio = new javax.swing.JRadioButton();
        positionradio = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(250, 270, 90, 40);

        model.setForeground(new java.awt.Color(255, 255, 255));
        model.setText("Bus Model");
        getContentPane().add(model);
        model.setBounds(160, 200, 90, 30);

        busmodelcombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BUGATTE", "AUDE", "PORCHE", "BNW", "BANS", "TOYATA" }));
        getContentPane().add(busmodelcombo);
        busmodelcombo.setBounds(270, 200, 140, 30);

        staffid.setForeground(new java.awt.Color(255, 255, 255));
        staffid.setText("Staff ID");
        getContentPane().add(staffid);
        staffid.setBounds(160, 140, 80, 30);
        getContentPane().add(staffcombo);
        staffcombo.setBounds(270, 140, 140, 30);
        getContentPane().add(idcombo);
        idcombo.setBounds(270, 80, 140, 30);

        busid.setForeground(new java.awt.Color(255, 255, 255));
        busid.setText("Bus ID");
        getContentPane().add(busid);
        busid.setBounds(160, 80, 80, 30);

        idradio.setOpaque(false);
        idradio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idradioActionPerformed(evt);
            }
        });
        getContentPane().add(idradio);
        idradio.setBounds(130, 80, 20, 30);

        nameradio.setOpaque(false);
        nameradio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameradioActionPerformed(evt);
            }
        });
        getContentPane().add(nameradio);
        nameradio.setBounds(130, 140, 20, 30);

        positionradio.setOpaque(false);
        positionradio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positionradioActionPerformed(evt);
            }
        });
        getContentPane().add(positionradio);
        positionradio.setBounds(130, 200, 20, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 570, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int i = 0;
        String s_id;
        String b_id;
        String b_model;
        i = radioselection();
        b_id = String.valueOf(idcombo.getSelectedItem());
        s_id = String.valueOf(staffcombo.getSelectedItem());
        b_model = String.valueOf(busmodelcombo.getSelectedItem());
        if (i == 0) {
            JOptionPane.showMessageDialog(null, "Please select the radio button.",
                    "Radio Button Error", JOptionPane.ERROR_MESSAGE);
        } else {
            new BusSearch_Record(i, b_id, s_id, b_model);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private int radioselection() {
        int i = 0;
        if (idradio.isSelected()) {
            i = 1;
        } else if (nameradio.isSelected()) {
            i = 2;
        } else if (positionradio.isSelected()) {
            i = 3;
        }
        return i;
    }
    private void idradioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idradioActionPerformed

    }//GEN-LAST:event_idradioActionPerformed

    private void nameradioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameradioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameradioActionPerformed

    private void positionradioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positionradioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_positionradioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search_Bus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search_Bus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search_Bus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search_Bus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Search_Bus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel busid;
    private javax.swing.JComboBox busmodelcombo;
    private javax.swing.ButtonGroup buttonradio;
    private javax.swing.JComboBox idcombo;
    private javax.swing.JRadioButton idradio;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel model;
    private javax.swing.JRadioButton nameradio;
    private javax.swing.JRadioButton positionradio;
    private javax.swing.JComboBox staffcombo;
    private javax.swing.JLabel staffid;
    // End of variables declaration//GEN-END:variables
}
