/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui.Maintenance.Bus;

import Control.*;
import Domain.Bus;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Guanhaochan
 */
public class Update_Bus extends javax.swing.JFrame {

    private String host = "jdbc:derby://localhost:1527/FYP database";
    private String user = "nbuser";
    private String password = "nbuser";
    private Connection conn;
    private PreparedStatement stmt;
    private PreparedStatement stmt1;
    private MaintainBusControl busControl;
    private Bus bus;

    public Update_Bus() {
        busControl = new MaintainBusControl();
        createConnection();
        initComponents();
        RetrieveStaffIDToComboBox();
        RetrieveBusIDToComboBox();
        busno.setEditable(false);
        seatno.setEditable(false);
        buscombo.setEnabled(false);
        staffcombo.setEnabled(false);
        jButton1.setEnabled(false);
        setSize(493, 362);
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        setTitle("Update Bus");
    }

    private void RetrieveStaffIDToComboBox() {
        try {
            String sql = "select * from STAFF WHERE POSITION = 'Bus Driver'";
            String sql1 = "select * from BUS";
            stmt = conn.prepareStatement(sql);
            stmt1 = conn.prepareStatement(sql1);
            ResultSet rs = stmt.executeQuery();
            ResultSet rs1 = stmt1.executeQuery();
            while (rs.next()) {

                String id = rs.getString(1);
                staffcombo.addItem(id);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    private void RetrieveBusIDToComboBox() {
        try {
            String sql = "select * from BUS";
            stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            while (rs.next()) {

                String id = rs.getString(1);
                busId.addItem(id);

            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    private void createConnection() {
        try {
            conn = DriverManager.getConnection(host, user, password);
            System.out.println("***TRACE: Connection established.");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void shutDown() {
        if (conn != null) {
            try {
                conn.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        stafflabel = new javax.swing.JLabel();
        staffcombo = new javax.swing.JComboBox();
        modellabel = new javax.swing.JLabel();
        buscombo = new javax.swing.JComboBox();
        seatlabel = new javax.swing.JLabel();
        busnolabel = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        busid = new javax.swing.JLabel();
        busId = new javax.swing.JComboBox();
        seatno = new javax.swing.JTextField();
        busno = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(240, 270, 90, 30);

        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(110, 270, 90, 30);

        stafflabel.setForeground(new java.awt.Color(255, 255, 255));
        stafflabel.setText("Staff ID");
        getContentPane().add(stafflabel);
        stafflabel.setBounds(90, 210, 100, 30);

        staffcombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-" }));
        getContentPane().add(staffcombo);
        staffcombo.setBounds(220, 210, 120, 30);

        modellabel.setForeground(new java.awt.Color(255, 255, 255));
        modellabel.setText("Bus Model");
        getContentPane().add(modellabel);
        modellabel.setBounds(90, 170, 100, 30);

        buscombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "BUGATTE", "AUDE", "PORCHE", "BNW", "BANS", "TOYATA" }));
        getContentPane().add(buscombo);
        buscombo.setBounds(220, 170, 120, 30);

        seatlabel.setForeground(new java.awt.Color(255, 255, 255));
        seatlabel.setText("Number of Seat");
        getContentPane().add(seatlabel);
        seatlabel.setBounds(90, 130, 100, 30);

        busnolabel.setForeground(new java.awt.Color(255, 255, 255));
        busnolabel.setText("Bus No");
        getContentPane().add(busnolabel);
        busnolabel.setBounds(90, 90, 60, 30);

        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search);
        search.setBounds(370, 50, 90, 30);

        busid.setForeground(new java.awt.Color(255, 255, 255));
        busid.setText("Bus ID");
        getContentPane().add(busid);
        busid.setBounds(90, 50, 60, 30);

        busId.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-" }));
        getContentPane().add(busId);
        busId.setBounds(220, 50, 120, 30);

        seatno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatnoActionPerformed(evt);
            }
        });
        seatno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                seatnoKeyTyped(evt);
            }
        });
        getContentPane().add(seatno);
        seatno.setBounds(220, 130, 120, 30);
        getContentPane().add(busno);
        busno.setBounds(220, 90, 120, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 490, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        busno.setText(null);
        seatno.setText(null);
        busno.setEditable(false);
        seatno.setEditable(false);
        busId.setSelectedItem("-");
        buscombo.setSelectedItem("-");
        staffcombo.setSelectedItem("-");
        buscombo.setEnabled(false);
        staffcombo.setEnabled(false);
        jButton1.setEnabled(false);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (validation() == true) {
            String id = String.valueOf(busId.getSelectedItem());
            String bus_no = busno.getText().toUpperCase();
            String model = String.valueOf(buscombo.getSelectedItem());
            String staff_id = String.valueOf(staffcombo.getSelectedItem());
            int seat = Integer.parseInt(seatno.getText());
            Bus bus = new Bus(id, bus_no, seat, model, staff_id);
            busControl.UpdateRecord(bus);
            JOptionPane.showMessageDialog(null, "New bus update successfully.",
                    "Bus Updated", JOptionPane.INFORMATION_MESSAGE);
            busno.setText(null);
            seatno.setText(null);
            busno.setEditable(false);
            seatno.setEditable(false);
            busId.setSelectedItem("-");
            buscombo.setSelectedItem("-");
            staffcombo.setSelectedItem("-");
            buscombo.setEnabled(false);
            staffcombo.setEnabled(false);
            jButton1.setEnabled(false);

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public boolean validation() {
        if ((busId.getSelectedItem() == "-")) {
            JOptionPane.showMessageDialog(null, "Please select the bus id",
                    "Invalid selection", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (busno.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Please enter the Bus No. eg.ABC1234",
                    "Invalid Bus No", JOptionPane.ERROR_MESSAGE);
            busno.grabFocus();
            return false;
        } else if ((busno.getText().trim().length() > 7)) {
            JOptionPane.showMessageDialog(null, "Please enter not more than 7  alphanumeric. eg.ABC1234",
                    "Invalid Format", JOptionPane.ERROR_MESSAGE);
            busno.grabFocus();
            return false;
        } else if ((busno.getText().trim().length() < 7)) {
            JOptionPane.showMessageDialog(null, "Please enter not less than 7  alphanumeric in Bus No.eg.ABC1234",
                    "Invalid Format Bus No", JOptionPane.ERROR_MESSAGE);
            busno.grabFocus();
            return false;
        } else if ((seatno.getText().trim().length() == 0)) {
            JOptionPane.showMessageDialog(null, "Please enter the Number of Seat. eg.25",
                    "Invalid Seat number", JOptionPane.ERROR_MESSAGE);
            seatno.grabFocus();
            return false;
        } else if ((seatno.getText().trim().length() > 2)) {
            JOptionPane.showMessageDialog(null, "Please not more than 2 numeric. eg.25",
                    "Invalid Format", JOptionPane.ERROR_MESSAGE);
            seatno.grabFocus();
            return false;
        } else if ((seatno.getText().trim().length() < 2)) {
            JOptionPane.showMessageDialog(null, "Please not less than 2 numeric. eg.25",
                    "Invalid Format", JOptionPane.ERROR_MESSAGE);
            seatno.grabFocus();
            return false;
        } else if ((busId.getSelectedItem() == "-")) {
            JOptionPane.showMessageDialog(null, "Please select the bus model",
                    "Invalid selection", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if ((busId.getSelectedItem() == "-")) {
            JOptionPane.showMessageDialog(null, "Please select the staff id",
                    "Invalid selection", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        if ((busId.getSelectedItem() == "-")) {
            JOptionPane.showMessageDialog(null, "Please select the bus id",
                    "Invalid selection", JOptionPane.ERROR_MESSAGE);
        } else {
            jButton1.setEnabled(true);
            String id = String.valueOf(busId.getSelectedItem());
            bus = busControl.selectRecord(id);

            busno.setText(bus.getBUS_NO());
            seatno.setText(String.valueOf(bus.getSEAT()));
            buscombo.setSelectedItem(bus.getBUS_MODEL());
            staffcombo.setSelectedItem(bus.getSTAFF_ID());
            busno.setEditable(true);
            seatno.setEditable(true);
            buscombo.setEnabled(true);
            staffcombo.setEnabled(true);
        }

    }//GEN-LAST:event_searchActionPerformed

    private void seatnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatnoActionPerformed

    }//GEN-LAST:event_seatnoActionPerformed

    private void seatnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_seatnoKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            evt.consume();
        }
    }//GEN-LAST:event_seatnoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update_Bus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update_Bus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update_Bus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update_Bus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update_Bus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox busId;
    private javax.swing.JComboBox buscombo;
    private javax.swing.JLabel busid;
    private javax.swing.JTextField busno;
    private javax.swing.JLabel busnolabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel modellabel;
    private javax.swing.JButton search;
    private javax.swing.JLabel seatlabel;
    private javax.swing.JTextField seatno;
    private javax.swing.JComboBox staffcombo;
    private javax.swing.JLabel stafflabel;
    // End of variables declaration//GEN-END:variables
}
